FROM nginx:latest

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/maps.conf /etc/nginx/maps.conf
COPY ./frontend /usr/share/nginx/html


